Test book controller
wolox-training/ss-rails pull request #13
Opened 2021-06-22 16:09 UTC by Sspadea

## Summary

- testing book controller
- shared_context authenticated_user

## Trello Card

https://trello.com/c/emwPLdT8/21-2-crear-tests-para-rutas-index-y-show-de-book

## Screenshots or Screencasts

<img width="1180" alt="Captura de Pantalla 2021-06-22 a la(s) 13 06 34" src="https://user-images.githubusercontent.com/85120909/122961553-e193a880-d35a-11eb-9c4b-bf94bc347876.png">

2021-06-22 22:21 UTC, blacksam07 requested changes

2021-06-22 22:21 UTC, blacksam07 commented on app/controllers/api/v1/books_controller.rb
> +      def index
if very different to #11

2021-06-23 19:20 UTC, redwarewolf requested changes

2021-06-23 19:20 UTC, redwarewolf commented on app/controllers/api/v1/books_controller.rb
> +        ])
This logic shouldn't be here but on a service.

2021-06-23 19:20 UTC, redwarewolf commented on app/controllers/api/v1/books_controller.rb
> +        book = Book.friendly.find(params[:id])
same here

2021-06-23 19:20 UTC, redwarewolf commented on spec/controllers/api/v1/books_controller_spec.rb
> +    context 'when fetching a book' do
And the bad scenario?

2021-06-23 19:20 UTC, redwarewolf commented on spec/controllers/api/v1/books_controller_spec.rb
> +    context 'when fetching all the books' do
and the bad scenario?

2021-06-28 14:58 UTC, redwarewolf approved these changes

2021-06-28 21:30 UTC, blacksam07 approved these changes

2021-06-28 21:31 UTC, merged