Created Book Suggestions model
wolox-training/ss-rails pull request #14
Opened 2021-06-22 18:04 UTC by Sspadea

## Summary

- Created book suggestions model

## Trello Card

https://trello.com/c/k26N27Gx/24-1-crear-modelo-de-booksuggestion

## Screenshots or Screencasts

<img width="1192" alt="Captura de Pantalla 2021-06-22 a la(s) 15 01 44" src="https://user-images.githubusercontent.com/85120909/122976691-08f27180-d36b-11eb-858e-bb4c4189d2e0.png">

2021-06-22 22:21 UTC, blacksam07 approved these changes

2021-06-23 19:21 UTC, redwarewolf requested changes

2021-06-23 19:21 UTC, redwarewolf commented on spec/factories/book_suggestions.rb
> +  end
Why is this empty?

2021-06-23 19:21 UTC, redwarewolf commented on spec/models/book_suggestion_spec.rb
> +end
You can use the shoulda_matchers here

2021-06-28 15:01 UTC, redwarewolf requested changes

2021-06-28 15:01 UTC, redwarewolf commented on spec/models/book_suggestion_spec.rb
> +      end
These can be replaced with the gem I suggested

2021-06-28 19:18 UTC, redwarewolf approved these changes

2021-06-28 21:33 UTC, merged