Route create booksuggestion
wolox-training/ss-rails pull request #15
Opened 2021-06-22 20:08 UTC by Sspadea

## Summary

- Route create book suggestion

## Trello Card

https://trello.com/c/CLEfey0g/25-1-crear-ruta-para-creaci%C3%B3n-de-un-booksuggestion

## Screenshots or Screencasts

<img width="1240" alt="Captura de Pantalla 2021-06-22 a la(s) 17 06 29" src="https://user-images.githubusercontent.com/85120909/122992318-5deab380-d37c-11eb-8d44-cd6ee4137c44.png">

2021-06-22 22:22 UTC, blacksam07 approved these changes

2021-06-23 19:37 UTC, redwarewolf requested changes

2021-06-23 19:37 UTC, redwarewolf commented on app/controllers/api/v1/book_suggestions_controller.rb
> +          render json: { errors: [{ code: '422', message: book_suggestion.errors }] }, status: :unprocessable_entity
I wouldn't say this is an unprocessable_entity.
Also move logic to a service.

2021-06-23 19:37 UTC, redwarewolf commented on app/helpers/book_suggestions_helper.rb
> +end
Why is this empty?

2021-06-23 19:37 UTC, redwarewolf commented on spec/helpers/book_suggestions_helper_spec.rb
> +end
whats with this file?

2021-06-23 19:37 UTC, redwarewolf commented on spec/controllers/book_suggestions_controller_spec.rb
> +RSpec.describe BookSuggestionsController, type: :controller do
shoulda matchers

2021-06-24 13:06 UTC, merged