Testing Create Route
wolox-training/ss-rails pull request #16
Opened 2021-06-22 20:53 UTC by Sspadea

## Summary

- Testing create route when is valid
- Testing create route when is invalid

## Trello Card

https://trello.com/c/Of3eJfzF/26-2-crear-test-para-endpoint-de-creaci%C3%B3n-de-un-booksuggestion

## Screenshots or Screencasts

<img width="1240" alt="Captura de Pantalla 2021-06-22 a la(s) 17 50 33" src="https://user-images.githubusercontent.com/85120909/122997677-9e4d3000-d382-11eb-97ce-4b4eb96c8ee1.png">

2021-06-22 22:23 UTC, blacksam07 requested changes

2021-06-22 22:23 UTC, blacksam07 commented on spec/controllers/api/v1/book_suggestions_controller_spec.rb
> +          post :create, params: { book_suggestion: new_book_suggestion_attributes }
you can define a subject whit the post request and use it

2021-06-23 19:39 UTC, redwarewolf requested changes

2021-06-23 19:39 UTC, redwarewolf commented on spec/controllers/api/v1/book_suggestions_controller_spec.rb
> +        expect(response).to have_http_status(:unprocessable_entity)
I dont think this is the right code. Id  say 400

2021-06-24 17:37 UTC, merged