create rent model
wolox-training/ss-rails pull request #17
Opened 2021-06-23 16:30 UTC by Sspadea

## Summary

- Rent model created

## Trello Card

https://trello.com/c/U6D65vgD/18-1-crear-modelo-de-rent

## Screenshots or Screencasts

<img width="1238" alt="Captura de Pantalla 2021-06-23 a la(s) 13 25 41" src="https://user-images.githubusercontent.com/85120909/123134200-efaefb00-d426-11eb-8787-74f0ce388a21.png">

2021-06-23 19:39 UTC, redwarewolf requested changes

2021-06-23 19:39 UTC, redwarewolf commented on spec/models/rent_spec.rb
> +end
👀

2021-06-28 15:03 UTC, redwarewolf requested changes

2021-06-28 15:03 UTC, redwarewolf commented on spec/factories/rents.rb
> +end
delete this hahahah

2021-06-28 19:18 UTC, redwarewolf approved these changes

2021-06-28 21:30 UTC, blacksam07 approved these changes

2021-07-05 13:11 UTC, redwarewolf approved these changes

2021-07-05 13:11 UTC, redwarewolf commented
Falta actualizar el Branch, hay conflictos

2021-07-07 14:43 UTC, merged