Endpoints for rents
wolox-training/ss-rails pull request #19
Opened 2021-06-25 15:03 UTC by Sspadea

## Summary

- Endpoint index with serializer and paginate
- Endpoint create

## Trello Card

https://trello.com/c/S8ws0jKe/27-2-crear-endpoint-de-creacion-de-rent-e-index-con-strong-params

## Screenshots or Screencasts

<img width="1200" alt="Captura de Pantalla 2021-06-25 a la(s) 11 58 59" src="https://user-images.githubusercontent.com/85120909/123444495-53633080-d5ad-11eb-9a78-27b2d533e5e2.png">

2021-06-28 19:08 UTC, redwarewolf approved these changes

2021-06-28 21:35 UTC, blacksam07 requested changes

2021-06-28 21:35 UTC, blacksam07 commented on app/controllers/api/v1/rents_controller.rb
> +        rent = Api::V1::RentService.new(rent_params, current_user).new_rent
👀

2021-07-05 13:16 UTC, redwarewolf approved these changes

2021-07-07 14:25 UTC, blacksam07 approved these changes

2021-07-07 14:44 UTC, merged