endpoints working
wolox-training/ss-rails pull request #20
Opened 2021-06-25 21:06 UTC by Sspadea

## Summary

- Endpoint book_rankings in order DESC
- Endpoint active in order ASC

## Trello card

https://trello.com/c/sv1V089a/52-crear-los-endpoints-book-rankings-y-active-rents-para-rents

## Screenshots or Screencasts

<img width="585" alt="Captura de Pantalla 2021-06-25 a la(s) 18 01 26" src="https://user-images.githubusercontent.com/85120909/123485178-f5037580-d5df-11eb-8de6-1a23cd1fd34e.png">
<img width="546" alt="Captura de Pantalla 2021-06-25 a la(s) 18 02 05" src="https://user-images.githubusercontent.com/85120909/123485184-f7fe6600-d5df-11eb-8f91-068d7c6bd0df.png">

2021-06-28 19:17 UTC, redwarewolf approved these changes

2021-06-28 19:17 UTC, redwarewolf commented on app/controllers/api/v1/rents_controller.rb
> +      end
I'd love to use metaprogramming here but don't mind me

2021-07-05 13:23 UTC, redwarewolf requested changes

2021-07-05 13:23 UTC, redwarewolf commented on app/models/rent.rb
> +    book_to_update.save
```
book_to_update = self.book
book_to_update.times_rented += 1
book_to_update.save
```
The find is redundant

2021-07-05 13:35 UTC, redwarewolf requested changes

2021-07-05 13:35 UTC, redwarewolf commented on app/models/rent.rb
> +    book_to_update.save
Also, if you want to know the amount of times the book was rented, you have to only count the rents that exist for this book.

`self.book.rents.count`

2021-07-07 14:25 UTC, blacksam07 approved these changes

2021-07-07 15:07 UTC, redwarewolf approved these changes

2021-07-07 15:08 UTC, merged