Creating user model
wolox-training/ss-rails pull request #4
Opened 2021-06-07 15:27 UTC by Sspadea

## Summary

- the devise gem was added
- the devise_token_auth gem was added
- first_name and last_name validations with presence: true

## Trello Card

https://trello.com/c/CeS8lgot/22-2-crear-modelo-de-user-implementar-autenticaci%C3%B3n

## Screenshots or Screencasts

<img width="1334" alt="Captura de Pantalla 2021-06-07 a la(s) 12 22 24" src="https://user-images.githubusercontent.com/85120909/121043892-6c857800-c78b-11eb-9942-d6af5486a0be.png">

2021-06-07 16:50 UTC, redwarewolf requested changes

2021-06-07 16:50 UTC, redwarewolf commented on app/models/user.rb
> +  validates :last_name, presence: true
Keep in mind that if you are gonna validate the presence of these 2 fields in the model, then the DB should have the same validation

2021-06-08 13:33 UTC, blacksam07 commented on app/controllers/application_controller.rb
> +  skip_before_action :verify_authenticity_token
delete this ins the future

2021-06-08 13:33 UTC, blacksam07 commented on app/models/user.rb
> +  validates :last_name, presence: true
add va.idations to email

2021-06-08 15:45 UTC, blacksam07 approved these changes

2021-06-10 12:55 UTC, redwarewolf approved these changes

2021-06-10 12:56 UTC, merged