Integrating external api
wolox-training/ss-rails pull request #5
Opened 2021-06-10 14:51 UTC by Sspadea

## Summary

- Openlibrary external api integrated.
- Gem HTTParty is not working, finally we decided to use gem faraday.
- The endpoint is already returning the information of any book using its isbn.

## Trello Card

https://trello.com/b/Y5WdkBZf/training-ror-sebastian-spadea

## Screenshots or Screencasts

<img width="1240" alt="Captura de Pantalla 2021-06-10 a la(s) 11 41 56" src="https://user-images.githubusercontent.com/85120909/121545974-58d34f00-c9e1-11eb-8b84-1c9b390c69e8.png">

2021-06-11 14:17 UTC, blacksam07 requested changes

2021-06-11 14:17 UTC, blacksam07 commented on app/controllers/api/v1/books_controller.rb
> +        book = open_library.fetch_data
```suggestion
        book = OpenLibrary.new(params[:isbn]).fetch_data
```

2021-06-11 14:17 UTC, blacksam07 commented on app/controllers/api/v1/books_controller.rb
> +            format.json { render json: { status: 'Success', message: 'Loaded book', data: book }, status: :ok }
Use only a `render` method is more clear 
Success request
```ruby
render json: book, status: :ok
```
Wrong request like 
```ruby
render json: { message: 'Lorem itsu' }, status: :unprocessable_entity
```

2021-06-11 14:17 UTC, blacksam07 commented on app/services/application_service.rb
> +class ApplicationService
Useless file

2021-06-11 14:17 UTC, blacksam07 commented on app/services/open_library.rb
> +  def books
rename this method like `find_book`

2021-06-11 14:17 UTC, blacksam07 commented on app/services/open_library.rb
> +    uri = "https://openlibrary.org/api/books?bibkeys=#{@isbn}&format=json&jscmd=data"
Use credentials to save the base `https://openlibrary.org/api` and merge with `/books` inside method, and remember to use the query params as JSON, you should define inside the initializer

```ruby
@options = { query: { bibkeys: "ISBN:#{isbn}", format: 'json', jscmd: 'data' } }

Faraday.get("#{base_url}/books", @options,
```

2021-06-11 14:17 UTC, blacksam07 commented on app/services/open_library.rb
> +    res.body != '{}' ? res.body : 'not found'
Use Json parse in body response and return, empty json or json with data

2021-06-11 14:17 UTC, blacksam07 commented on app/services/open_library.rb
> +      response['authors'] = take_authors(response['authors'])
move this logic to external method

2021-06-11 14:17 UTC, blacksam07 commented on config/routes.rb
> +      get "/books/:isbn" => "books#info"
use resources 

```ruby
resources :open_library, only: :show, param: :isbn
```

2021-06-11 19:23 UTC, blacksam07 commented on app/assets/stylesheets/open_library.scss
> +// Place all the styles related to the open_library controller here.
Useless file

2021-06-11 19:23 UTC, blacksam07 commented on app/helpers/open_library_helper.rb
> +module OpenLibraryHelper
Useless file

2021-06-11 19:23 UTC, blacksam07 commented on app/services/open_library.rb
> +    @base_url = 'https://openlibrary.org/api'
Use credentials to save the url https://blog.saeloun.com/2019/10/10/rails-6-adds-support-for-multi-environment-credentials.html#in-rails-6

2021-06-11 19:24 UTC, blacksam07 approved these changes

2021-06-14 13:42 UTC, redwarewolf requested changes

2021-06-14 13:42 UTC, redwarewolf commented on app/controllers/open_library_controller.rb
> +      render json: book, status: :ok
The status and response isn't right. When you can't find a book it's 404 resource not found.
You can read more about it here: https://github.com/Wolox/tech-guides/blob/master/backend/backend-standard-and-best-practices.md#32--error-forwarding

Basically the response should be: { error: { some error and message}, status: status_code }

2021-06-14 13:42 UTC, redwarewolf commented on app/services/open_library.rb
> +    byebug
Oops 👀

2021-06-14 13:42 UTC, redwarewolf commented on app/services/open_library.rb
> +    url = "#{Rails.application.credentials.config[:url]}/books"
This should be a constant outside the method

2021-06-14 13:47 UTC, redwarewolf commented on app/services/open_library.rb
> +    byebug
@blacksam07 :shame: jajajajaja

2021-06-14 15:07 UTC, redwarewolf approved these changes

2021-06-14 15:08 UTC, merged